import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_EN': {
          'change language': "Change Language",
          'continue': "Continue",
          'login': "Log In",
          'email': "Email:",
          'password': "Password:",
          'forgotpassword': "Forgot Password",
          'newuser': "New User?",
          'signup': "Sign Up",
          'home': "Home",
          'know your water footprint': "Know your water Footprint",
          'homedesc':
              "Water footprint is the amount of water used to produce the goods and services we consume",
          'scanit': "Scan It",
          'entermanually': "Enter Manually",
          'enterdetails': "Enter Details",
          'calculate': "Calculate",
          'productname': "Product Name",
          'scan': 'Scan',
          'image': 'Image:',
          'water footprint': 'Water Footprint:',
          'loading preview': 'Loading Preview...',
          'english': 'English',
          'hindi': 'Hindi',
          'bengali': 'Bengali',
          'kanada': 'Kanada',
          'marathi': 'Marathi',
          'oriya': 'Oriya',
        },
        'hi_HI': {
          'change language': "भाषा बदलें",
          'continue': "जारी रखना",
          'login': "लॉग इन करो",
          'email': "ईमेल",
          'password': "पासवर्ड",
          'forgotpassword': "पासवर्ड भूल गए",
          'newuser': "नए उपयोगकर्ता?",
          'signup': "साइन इन करें",
          'home': "होम",
          'know your water footprint': "अपने वाटर फुटप्रिंट को जानें",
          'homedesc':
              "वाटर फुटप्रिंट हमारे द्वारा उपभोग की जाने वाली वस्तुओं और सेवाओं के उत्पादन के लिए उपयोग किए जाने वाले पानी की मात्रा है",
          'scanit': "स्कैन करें",
          'entermanually': "मैन्युअल रूप से दर्ज करें",
          'enterdetails': "विवरण दर्ज करें",
          'calculate': "हिसाब लगाना",
          'productname': "प्रोडक्ट का नाम",
          'scan': 'स्कैन',
          'image': 'छवि:',
          'water footprint': 'जल पदचिह्न:',
          'loading preview': 'लोड हो रहा है...',
          'english': 'अंग्रेज़ी',
          'hindi': 'हिन्दी',
          'bengali': 'बांग्ला',
          'kannada': 'कन्नड़',
          'marathi': 'मराठी',
          'odia': 'ओडिया',
        },
        'bn_BN': {
          'change language': "ভাষা পরিবর্তন করুন",
          'continue': "চালিয়ে যান",
          'login': "লগ ইন",
          'email': "ইমেইল",
          'password': "পাসওয়ার্ড",
          'forgotpassword': "পাসওয়ার্ড ভুলে গেছি",
          'newuser': "নতুন ব্যবহারকারী?",
          'signup': "সাইন ইন করুন",
          'home': "বাড়ি",
          'know your water footprint': "আপনার জল পদচিহ্ন জানুন",
          'homedesc':
              "ওয়াটার ফুটপ্রিন্ট হল আমরা যে পণ্য এবং পরিষেবাগুলি ব্যবহার করি তা উত্পাদন করতে ব্যবহৃত জলের পরিমাণ",
          'scanit': "স্ক্যান",
          'entermanually': "ম্যানুয়ালি প্রবেশ করুন",
          'enterdetails': "বিস্তারিত লিখুন",
          'calculate': "গণনা করতে",
          'productname': "পণ্যের নাম",
          'scan': 'স্ক্যান',
          'image': 'ইমেজ:',
          'water footprint': 'জলের পদচিহ্ন:',
          'loading preview': 'এটা লোড হচ্ছে...',
          'english': 'ইংরেজি',
          'hindi': 'হিন্দি',
          'bengali': 'বাংলা',
          'kannada': 'কন্নড়',
          'marathi': 'মারাঠি',
          'odia': 'ওডিয়া',
        },
        'kn_KN': {
          'change language': "ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸಿ",
          'continue': "ಮುಂದುವರಿಸಿ",
          'login': "ಲಾಗ್ ಇನ್ ಮಾಡಿ",
          'email': "ಇಮೇಲ್",
          'password': "ಪಾಸ್ವರ್ಡ್",
          'forgotpassword': "ಪಾಸ್ವರ್ಡ್ ಮರೆತುಹೋಗಿದೆ",
          'newuser': "ಹೊಸ ಬಳಕೆದಾರರೇ?",
          'signup': "ಸೈನ್ ಇನ್ ಮಾಡಿ",
          'home': "ಮನೆ",
          'know your water footprint':
              "ನಿಮ್ಮ ನೀರಿನ ಹೆಜ್ಜೆಗುರುತನ್ನು ತಿಳಿದುಕೊಳ್ಳಿ",
          'homedesc':
              "ನೀರಿನ ಹೆಜ್ಜೆಗುರುತು ಎಂದರೆ ನಾವು ಬಳಸುವ ಸರಕು ಮತ್ತು ಸೇವೆಗಳನ್ನು ಉತ್ಪಾದಿಸಲು ಬಳಸುವ ನೀರಿನ ಪ್ರಮಾಣ",
          'scanit': "ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
          'entermanually': "ಹಸ್ತಚಾಲಿತವಾಗಿ ನಮೂದಿಸಿ",
          'enterdetails': "ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
          'calculate': "ಲೆಕ್ಕಾಚಾರ ಮಾಡಲು",
          'productname': "ಉತ್ಪನ್ನದ ಹೆಸರು",
          'scan': 'ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
          'image': 'ಚಿತ್ರ:',
          'water footprint': 'ನೀರಿನ ಹೆಜ್ಜೆಗುರುತು:',
          'loading preview': 'ಇದು ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
          'english': 'ಇಂಗ್ಲೀಷ್',
          'hindi': 'ಹಿಂದಿ',
          'bengali': 'ಬಾಂಗ್ಲಾ',
          'kannada': 'ಕನ್ನಡ',
          'marathi': 'ಮರಾಠಿ',
          'odia': 'ওডিয়া',
        },
      };
}
